# -*- coding: utf-8 -*-
"""
STEP 1 - INTRODUCTION TO PYTHON 2/2

Created on Wed Dec 30 23:14:33 2020

@author: Virgílio Matos Silva
"""

#--------------------------#
moma = [['Dress MacLeod from Tartan Sets',
  'Sarah Charlesworth',
  '(American)',
  '(1947)',
  '(2013)',
  '(Female)',
  '1986',
  'Prints & Illustrated Books'],
 ['Duplicate of plate from folio 11 verso (supplementary suite, plate 4) from ARDICIA',
  'Pablo Palazuelo',
  '(Spanish)',
  '(1916)',
  '(2007)',
  '(Male)',
  '1978',
  'Prints & Illustrated Books'],
 ['Tailpiece (page 55) from SAGESSE',
  'Maurice Denis',
  '(French)',
  '(1870)',
  '(1943)',
  '(Male)',
  '1889-1911',
  'Prints & Illustrated Books'],
 ['Headpiece (page 129) from LIVRET DE FOLASTRIES, À JANOT PARISIEN',
  'Aristide Maillol',
  '(French)',
  '(1861)',
  '(1944)',
  '(Male)',
  '1927-1940',
  'Prints & Illustrated Books'],
 ['97 rue du Bac',
  'Eugène Atget',
  '(French)',
  '(1857)',
  '(1927)',
  '(Male)',
  '1903',
  'Photography'],
 ['Pictorial ornament (folio 11) from WOODCUTS',
  'Antonio Frasconi',
  '(American)',
  '(1919)',
  '(2013)',
  '(Male)',
  '1957',
  'Prints & Illustrated Books'],
 ["Rue de l'Hôtel-de-Ville",
  'Eugène Atget',
  '(French)',
  '(1857)',
  '(1927)',
  '(Male)',
  '1924',
  'Photography'],
 ['Los Angeles Airport',
  'Garry Winogrand',
  '(American)',
  '(1928)',
  '(1984)',
  '(Male)',
  '1978-1983',
  'Photography'],
 ['Why Defy from Disasters of Peace',
  'Diane Victor',
  '(South African)',
  '(1964)',
  '',
  '(Female)',
  '2001',
  'Prints & Illustrated Books'],
 ['STILL WATER AND FISH',
  'David Brown Milne',
  '(Canadian)',
  '(1882)',
  '(1953)',
  '(Male)',
  '(1941)',
  'Prints & Illustrated Books'],
 ['In-text plate (folio 11) from LA MÉTROMANIE',
  'Jean Dubuffet',
  '(French)',
  '(1901)',
  '(1985)',
  '(Male)',
  '1949-1950',
  'Prints & Illustrated Books'],
 ['Black Bathroom',
  'Jim Dine',
  '(American)',
  '(1935)',
  '',
  '(Male)',
  '1963',
  'Prints & Illustrated Books'],
 ['In-text plate (page 108) from LYSISTRATA',
  'František Kupka',
  '(Czech)',
  '(1871)',
  '(1957)',
  '(Male)',
  '1908-1911',
  'Prints & Illustrated Books'],
 ['Transcendence. Designs for the Ballet',
  'Franklin Chenault Watkins',
  '(American)',
  '(1894)',
  '(1972)',
  '(Male)',
  '(1934)',
  'Drawings'],
 ['Untitled',
  'Christopher Wool',
  '(American)',
  '(1955)',
  '',
  '(Male)',
  '1997',
  'Prints & Illustrated Books'],
 ['Isadora Duncan',
  'Abraham Walkowitz',
  '(American)',
  '(1878)',
  '(1965)',
  '(Male)',
  '(1931-1933)',
  'Drawings'],
 ["L'Avenir de la Propriété",
  'Pierre Alechinsky',
  '(Belgian)',
  '(1927)',
  '',
  '(Male)',
  '1972',
  'Prints & Illustrated Books'],
 ['Arundel Castle from Black Series I',
  'Frank Stella',
  '(American)',
  '(1936)',
  '',
  '(Male)',
  '1967',
  'Prints & Illustrated Books'],
 ['Block fragments from the Samuel Freeman House, Los Angeles, CA',
  'Frank Lloyd Wright',
  '(American)',
  '(1867)',
  '(1959)',
  '(Male)',
  '1923-1924',
  'Architecture & Design'],
 ['Plate (folio 35) from ACORDE',
  'Vicente Rojo',
  '(Spanish)',
  '(1932)',
  '',
  '(Male)',
  '1979',
  'Prints & Illustrated Books'],
 ['Wolf House, Gubin, Poland (Third floor plan)',
  'Ludwig Mies van der Rohe',
  '(American)',
  '(1886)',
  '(1969)',
  '(Male)',
  '1925-1927',
  'Architecture & Design'],
 ['SA. Sovremennaia Arkhitektura (CA. Contemporary Architecture), no. 5',
  'Varvara Stepanova',
  '(Russian)',
  '(1894)',
  '(1958)',
  '(Female)',
  '1929',
  'Prints & Illustrated Books'],
 ['Untitled',
  'Richard Serra',
  '(American)',
  '(1938)',
  '',
  '(Male)',
  '1972',
  'Drawings'],
 ['Research on the Origin',
  'Robert Filliou',
  '(French)',
  '(1926)',
  '(1987)',
  '(Male)',
  '1974',
  'Prints & Illustrated Books'],
 ['Plate (folio 17) from KAFKA',
  'Roger Chancel',
  '(French)',
  '(1898)',
  '(1976)',
  '(Male)',
  '1957',
  'Prints & Illustrated Books'],
 ['Tailpiece (page 35) from SAINTE MONIQUE',
  'Pierre Bonnard',
  '(French)',
  '(1867)',
  '(1947)',
  '(Male)',
  '1920-1930',
  'Prints & Illustrated Books'],
 ['Bowl',
  'Jacqueline Poncelet',
  '(British)',
  '(1947)',
  '',
  '(Female)',
  '1974',
  'Architecture & Design'],
 ['Tailpiece (folio 42 verso) from LES AMOURS',
  'Émile Bernard',
  '(French)',
  '(1868)',
  '(1941)',
  '(Male)',
  '1915',
  'Prints & Illustrated Books'],
 ['Tuileries (vase)',
  'Eugène Atget',
  '(French)',
  '(1857)',
  '(1927)',
  '(Male)',
  '1912',
  'Photography'],
 ['Plate 23 (folio 25) from MALELADE',
  'Georg Baselitz',
  '(German)',
  '(1938)',
  '',
  '(Male)',
  '1988-1990',
  'Prints & Illustrated Books'],
 ['Duplicate of plate from folio 104 (supplementary suite, plate 95) from LA VILLE',
  'Frans Masereel',
  '(Belgian)',
  '(1889)',
  '(1972)',
  '(Male)',
  '1925',
  'Prints & Illustrated Books'],
 ['Untitled', 'Unknown', '()', '', '', '()', 'c. 1925', 'Photography'],
 ['Plate (folio 28) from Six Geometric Figures and All Their Combinations, Volume I',
  'Sol LeWitt',
  '(American)',
  '(1928)',
  '(2007)',
  '(Male)',
  '1980',
  'Prints & Illustrated Books'],
 ['Chamber Music',
  'James Tenney',
  '(American)',
  '(1934)',
  '(2006)',
  '(Male)',
  '1964',
  'Prints & Illustrated Books'],
 ['Plate (following folio V) from NOTES',
  'Claes Oldenburg',
  '(American)',
  '(1929)',
  '',
  '(Male)',
  '1968',
  'Prints & Illustrated Books'],
 ['Chocolate Object (Schokolade-Objekt)',
  'Dieter Roth',
  '(Swiss)',
  '(1930)',
  '(1998)',
  '(Male)',
  '1969',
  'Prints & Illustrated Books'],
 ["Mandry Ven'iamyna Tret'oho",
  'Moisei Fradkin',
  '()',
  '',
  '',
  '(Male)',
  '1934',
  'Prints & Illustrated Books'],
 ['Dust jacket front (duplicate of folder front) from 2 POEMAS',
  'Antonio Frasconi',
  '(American)',
  '(1919)',
  '(2013)',
  '(Male)',
  '1953',
  'Prints & Illustrated Books'],
 ['Fun City from Fun City',
  'Richard Lindner',
  '(American)',
  '(1901)',
  '(1978)',
  '(Male)',
  '1971',
  'Prints & Illustrated Books'],
 ['Angels from Witebsk',
  'Wojciech Prazmowski',
  '(Polish)',
  '(1949)',
  '',
  '(Male)',
  '1988',
  'Photography'],
 ['Tailpiece (page 62) from FABLES',
  'Thomas Bewick',
  '(British)',
  '(1753)',
  '(1828)',
  '(Male)',
  '1818',
  'Prints & Illustrated Books'],
 ['Untitled',
  'Spencer Sweeney',
  '(American)',
  '(1973)',
  '',
  '(Male)',
  '2002',
  'Drawings'],
 ['Variety',
  'Batiste Madalena',
  '(American)',
  '(1902)',
  '(1988)',
  '(Male)',
  '1926',
  'Film'],
 ['Stars and Disasters (Astres et Désastres)',
  'Pierre Alechinsky',
  '(Belgian)',
  '(1927)',
  '',
  '(Male)',
  '1969',
  'Prints & Illustrated Books'],
 ['U.S. Embassy Building, Tokyo Project (Aerial perspective)',
  'Frank Lloyd Wright',
  '(American)',
  '(1867)',
  '(1959)',
  '(Male)',
  '1914',
  'Architecture & Design'],
 ['Tuesday, Dec. 18, 1979',
  'On Kawara',
  '(Japanese)',
  '(1933)',
  '',
  '(Male)',
  '1979',
  'Painting & Sculpture'],
 ['Bank by Andy Warhol. Gaudy Savings by RCA Color Scanner. Pretty as a Pigture, Huh?',
  'Andy Warhol',
  '(American)',
  '(1928)',
  '(1987)',
  '(Male)',
  '1968',
  'Architecture & Design'],
 ['Pittsburgh, Pennsylvania',
  'Lee Friedlander',
  '(American)',
  '(1934)',
  '',
  '(Male)',
  '1979',
  'Photography'],
 ['Double page plate (between pages 96 and 97) from UBU ROI',
  'Joan Miró',
  '(Spanish)',
  '(1893)',
  '(1983)',
  '(Male)',
  '1966',
  'Prints & Illustrated Books'],
 ['Unity Temple, Oak Park, IL',
  'Frank Lloyd Wright',
  '(American)',
  '(1867)',
  '(1959)',
  '(Male)',
  '1904',
  'Architecture & Design'],
 ['PORTRAITS DE CHOPIN',
  'Marc Chagall',
  '(French)',
  '(1887)',
  '(1985)',
  '(Male)',
  '1949',
  'Prints & Illustrated Books'],
 ['The Razorback Bunch (Etching III)',
  'Robert Rauschenberg',
  '(American)',
  '(1925)',
  '(2008)',
  '(Male)',
  '1981',
  'Prints & Illustrated Books'],
 ['Identity Transfer from Program One: Aspen Projects',
  'Dennis Oppenheim',
  '(American)',
  '(1938)',
  '(2011)',
  '(Male)',
  '1970',
  'Media and Performance Art'],
 ['Lipstick (Ascending) on Caterpillar Track',
  'Claes Oldenburg',
  '(American)',
  '(1929)',
  '',
  '(Male)',
  '1969',
  'Prints & Illustrated Books'],
 ['"1 PERSON/1 PLACE" from the portfolio DETAILS FROM THE EXCAVATION OF WOOSTER STREET',
  'Richard Nonas',
  '(American)',
  '(1936)',
  '',
  '(Male)',
  '1972',
  'Prints & Illustrated Books'],
 ['Bagatelle',
  'Eugène Atget',
  '(French)',
  '(1857)',
  '(1927)',
  '(Male)',
  '1923-1925',
  'Photography'],
 ['The Barbie Doll Drawings #27',
  'Adrian Piper',
  '(American)',
  '(1948)',
  '',
  '(Female)',
  '1967',
  'Drawings'],
 ['Gericke House, project, Berlin-Wannsee, Germany, Landscape model',
  'Ludwig Mies van der Rohe',
  '(American)',
  '(1886)',
  '(1969)',
  '(Male)',
  '1932',
  'Architecture & Design'],
 ['Plate (page 209) from LES PETITES FLEURS',
  'Émile Bernard',
  '(French)',
  '(1868)',
  '(1941)',
  '(Male)',
  '1928',
  'Prints & Illustrated Books'],
 ['Mechanical for Ticket for Fluxorchestra at Carnegie Hall, Carnegie Recital Hall, New York, September 25, 1965',
  'George Maciunas',
  '(American)',
  '(1931)',
  '(1978)',
  '(Male)',
  '1965',
  'Prints & Illustrated Books'],
 ['Untitled',
  'Louise Bourgeois',
  '(American)',
  '(1911)',
  '(2010)',
  '(Female)',
  '2003',
  'Prints & Illustrated Books'],
 ['Banco Pinto & Sotto Mayor, Oliveira de Azeméis, Portugal, Plan sketch',
  'Álvaro Siza',
  '(Portuguese)',
  '(1933)',
  '',
  '(Male)',
  '1971-1974',
  'Architecture & Design'],
 ['Overcast Dusk-Glassy Lake from Loon Lake: Eleven Drawings',
  'Ellen Phelan',
  '(American)',
  '(1943)',
  '',
  '(Female)',
  '1983',
  'Drawings'],
 ['Golf Club Project, Krefeld, Germany',
  'Ludwig Mies van der Rohe',
  '(American)',
  '(1886)',
  '(1969)',
  '(Male)',
  '1930',
  'Architecture & Design'],
 ['Stamp Box',
  'Josef Hoffmann',
  '(Austrian)',
  '(1870)',
  '(1956)',
  '(Male)',
  '1946',
  'Architecture & Design'],
 ['Library, Villeurbanne, France, Interior rear elevation',
  'Mario Botta',
  '(Swiss)',
  '(1943)',
  '',
  '(Male)',
  '1984',
  'Architecture & Design']];

num_rows = len(moma)

#--------------------------#
opened_file = open('artworks.csv')
read_file = reader(opened_file)
moma = list(read_file)
moma = moma [1:]

#--------------------------#
age2 = age1.replace('one','two')

#--------------------------#
for instance in moma:
   # nationality = instance [2]
   # instance [2] = nationality.replace('(','').replace(')','')
    instance [2] = instance [2].replace('(','').replace(')','')
    instance [5] = instance [5].replace('(','').replace(')','')
    
#--------------------------#
for art in moma:
    gender = art [5]
    if not gender:
        art [5] = 'Gender Unknown/Other'
    else:
        art [5] = gender.title()
        
    nationality = art [2]
    if not nationality:
        art [2] = 'Nationality Unknown'
    else:
        art [2] = nationality.title()
        
#--------------------------#
def clean_and_convert(date):
    # check that we don't have an empty string
    if date != "":
        # move the rest of the function inside
        # the if statement
        date = date.replace("(", "")
        date = date.replace(")", "")
        date = int(date)
    return date

for art in moma:
    BeginDate = art [3]
    EndDate = art [4]
    
    art [3] = clean_and_convert(BeginDate)
    art [4] = clean_and_convert(EndDate)
    
#--------------------------#
test_data = ["1912", "1929", "1913-1923",
             "(1951)", "1994", "1934",
             "c. 1915", "1995", "c. 1912",
             "(1988)", "2002", "1957-1959",
             "c. 1955.", "c. 1970's", 
             "C. 1990-1999"]

bad_chars = ["(",")","c","C",".","s","'", " "]

def strip_characters(fDate):
    for f in bad_chars:
        fDate = fDate.replace(f,'')
    
    return fDate

stripped_test_data =[]

for each in test_data:
    stripped_test_data.append(strip_characters(each))
    
#--------------------------#
def process_date(date):
    if '-' in date:
        a, b = date.split('-')
        cDate = round((int(a)+int(b))/2)
    else:
        cDate = int(date)
        
    return cDate

        
processed_test_data = []

for each in stripped_test_data:
    processed_test_data.append(process_date(each))
    
for art in moma:
    art [6] = process_date(strip_characters(art [6]))
    
#--------------------------#
#--------------------------#
#--------------------------#
#--------------------------#